context:
  name: bioconductor-rhdf5lib
  version: "1.32.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://bioconductor.org/packages/3.22/bioc/src/contrib/Rhdf5lib_${{ version }}.tar.gz
  sha256: be6e080b0f8c91eea2761cb10b910036c00bcad6866dc4d285411a7ca4400fc4

build:
  number: 0
  script:
    - R CMD INSTALL --build .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
  host:
    - r-base >=4.2.0
  run:
    - r-base >=4.2.0

tests:
  - script:
    - Rscript -e "library('Rhdf5lib')"
  - script:
    - Rscript -e "library('Rhdf5lib'); packageVersion('Rhdf5lib')"

about:
  homepage: https://github.com/Huber-group-EMBL/Rhdf5lib
  summary: C and C++ HDF5 libraries
  description: |
    Provides C and C++ hdf5 libraries. This package ships the HDF5 C library
    for use by other R packages that need to link against it.
  license: Artistic-2.0
  license_file: LICENSE
  repository: https://github.com/Huber-group-EMBL/Rhdf5lib
  documentation: https://bioconductor.org/packages/release/bioc/html/Rhdf5lib.html

extra:
  recipe-maintainers:
    - btraven00
  bioconductor:
    package: Rhdf5lib
    version: 3.22
