context:
  name: bioconductor-dir.expiry
  version: "1.18.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://bioconductor.org/packages/3.22/bioc/src/contrib/dir.expiry_${{ version }}.tar.gz
  sha256: 71c3377b2388492e437443e72114741db9cebede67e5583cf8621cd9552eedc1


build:
  number: 0
  skip:
    - win
  script:
    - R CMD INSTALL --build .


requirements:
  host:
    - r-base >=4.5.0
    - r-filelock
  run:
    - r-base >=4.5.0
    - r-filelock

tests:
  - script:
    - Rscript -e "library('dir.expiry')"
  - script:
    - Rscript -e "library('dir.expiry'); packageVersion('dir.expiry')"

about:
  homepage: https://www.bioconductor.org/packages/release/bioc/html/dir.expiry.html
  summary: Managing Expiration for Cache Directories
  description: |
    Implements an expiration system for access to versioned directories. Directories 
    that have not been accessed by a registered function within a certain time frame 
    are deleted. This aims to reduce disk usage by eliminating obsolete caches 
    generated by old versions of packages.
  license: GPL-3.0-only
  repository: https://github.com/LTLA/dir.expiry
  documentation: https://www.bioconductor.org/packages/release/bioc/html/dir.expiry.html

extra:
  recipe-maintainers:
    - markrobinsonuzh
  bioconductor:
    package: dir.expiry
    version: 3.22
